### ISSUE TITLE
README.md의 비용 기능 관련

### ISSUE THREAD

**Issue by litsynp** [caumannerman/Swift_QuoteGeneratorApp#1]
README.md 에 있는 화면 내의 `비용`은 무슨 기능인가요?

**Comment by caumannerman** [comment]
명언을 남긴 사람의 이름입니다!

**Comment by caumannerman** [comment]
> README.md 에 있는 화면 내의 `비용`은 무슨 기능인가요?

명언을 남긴 사람의 이름입니다! 예시가 부족했네요 :)
